version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smart_absen_mysql
    environment:
      MYSQL_ROOT_PASSWORD: SmartAbsen2025!
      MYSQL_DATABASE: smart_absen
      MYSQL_USER: absen_user
      MYSQL_PASSWORD: AbsenPass2025!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
